name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Linting with pylint
        run: docker-compose run app sh -c "pylint api --load-plugins=pylint_django --django-settings-module=api.settings"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Testing with Django
        run: docker-compose run app sh -c "python manage.py test"
